# TODO: Consider using versioned tags instead of 'latest' for better control in production.
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "REACT_APP_LOGIN_URL = $REACT_APP_LOGIN_URL"
      - echo "REACT_APP_LOGOUT_URL = $REACT_APP_LOGOUT_URL"
  build:
    commands:
      - echo "Build started on $(date)"

      - echo "Building Docker image for Main Application..."
      - >
        docker build --build-arg REACT_APP_LOGIN_URL=$REACT_APP_LOGIN_URL --build-arg REACT_APP_LOGOUT_URL=$REACT_APP_LOGOUT_URL -t memoria-main-app:latest ./main_application
        || echo "Docker build for Main Application failed"
      - >
        docker tag memoria-main-app:latest
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/memoria-docker-images:memoria-main-app-latest
        || echo "Docker tagging failed"

      - echo "Building Docker image for Analytics Service..."
      - >
        docker build -t memoria-analytics-service:latest .
        || echo "Docker build for Analytics Service failed"
      - >
        docker tag memoria-analytics-service:latest
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/memoria-docker-images:memoria-analytics-service-latest ./analytics_service
        || echo "Docker tagging failed"
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image for Main Application...
      - >
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/memoria-docker-images:memoria-main-app-latest
        || echo "Docker push failed"

      - echo Pushing the Docker image for Analytics Service...
      - >
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/memoria-docker-images:memoria-analytics-service-latest
        || echo "Docker push failed"
artifacts:
  files:
    - Dockerrun.aws.json
    - .platform/nginx/conf.d/proxy.conf
